const allAlbums = [
  {
    artist: "TXT",
    albumName: "Lightstick [Ver.1]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "txt-lightstick1.webp",
  },
  {
    artist: "TXT",
    albumName: "Lightstick [Ver.2]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "txt-lightstick2.webp",
  },
  {
    artist: "TXT",
    albumName: "The Dream Chapter: STAR",
    owned: true,
    wishlist: false,
    notes: "",
    img: "tdc-star.jpg",
  },
  {
    artist: "TXT",
    albumName: "The Dream Chapter: MAGIC [Sanctuary]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "tdc-sanctuary.webp",
  },
  {
    artist: "TXT",
    albumName: "The Dream Chapter: MAGIC [Arcadia]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "tdc-arcadia.webp",
  },
  {
    artist: "TXT",
    albumName: "The Dream Chapter: ETERNITY [Port]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "tdc-port.webp",
  },
  {
    artist: "TXT",
    albumName: "The Dream Chapter: ETERNITY [Starboard]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "tdc-starboard.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 1: Blue Hour [R]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "mini1-r.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 1: Blue Hour [AR]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "mini1-ar.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 1: Blue Hour [VR]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "mini1-vr.webp",
  },
  {
    artist: "TXT",
    albumName: "The Chaos Chapter: FREEZE [World]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tcc-world.webp",
  },
  {
    artist: "TXT",
    albumName: "The Chaos Chapter: FREEZE [You]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "tcc-you.webp",
  },
  {
    artist: "TXT",
    albumName: "The Chaos Chapter: FREEZE [Boy]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tcc-boy.webp",
  },
  {
    artist: "TXT",
    albumName: "Chaotic Wonderland [A]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "chaoticwonderland-a.webp",
  },
  {
    artist: "TXT",
    albumName: "Chaotic Wonderland [B]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "chaoticwonderland-b.webp",
  },
  {
    artist: "TXT",
    albumName: "Chaotic Wonderland [Standard]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "chaoticwonderland-standard.webp",
  },
  {
    artist: "TXT",
    albumName: "The Chaos Chapter: FIGHT OR ESCAPE [Fight]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "tcc-fight.webp",
  },
  {
    artist: "TXT",
    albumName: "The Chaos Chapter: FIGHT OR ESCAPE [Escape]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tcc-escape.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 2: Thursday's Child [Hate]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "mini2-tc-hate.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 2: Thursday's Child [End]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "mini2-tc-end.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 2: Thursday's Child [Mess]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "mini2-tc-mess.webp",
  },
  {
    artist: "TXT",
    albumName: "Good Boy Gone Bad [Standard]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "gbgb-standard.jpg",
  },
  {
    artist: "TXT",
    albumName: "Good Boy Gone Bad [Limited]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "gbgb-limited.jpg",
  },
  {
    artist: "TXT",
    albumName: "The Name Chapter: TEMPTATION [Daydream]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tnc-t-daydream.webp",
  },
  {
    artist: "TXT",
    albumName: "The Name Chapter: TEMPTATION [Nightmare]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tnc-t-nightmare.webp",
  },
  {
    artist: "TXT",
    albumName: "The Name Chapter: TEMPTATION [Farewell]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "tnc-t-farewell.webp",
  },
  {
    artist: "TXT",
    albumName: "The Name Chapter: FREEFALL [Reality]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tnc-reality.webp",
  },
  {
    artist: "TXT",
    albumName: "The Name Chapter: FREEFALL [Melancholy]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tnc-melancholy.webp",
  },
  {
    artist: "TXT",
    albumName: "The Name Chapter: FREEFALL [Clarity]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tnc-clarity.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 3: TOMORROW [Ethereal]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "mini3-ethereal.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 3: TOMORROW [Romantic]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "mini3-romantic.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 3: TOMORROW [Promise]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "mini3-promise.webp",
  },
  {
    artist: "TXT",
    albumName: "Minisode 3: TOMORROW [Light]",
    owned: false,
    wishlist: true,
    notes: "Pls the Beomgyu version asdlfkajdflajdfla",
    img: "mini3-light.webp",
  },
  {
    artist: "TXT",
    albumName: "The Star Chapter: SANCTUARY [Angel]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "tsc-angel.webp",
  },
  {
    artist: "TXT",
    albumName: "The Star Chapter: SANCTUARY [Knight]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "tsc-knight.webp",
  },
  {
    artist: "TXT",
    albumName: "The Star Chapter: SANCTUARY [Savior]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "tsc-savior.webp",
  },
  {
    artist: "TXT",
    albumName: "The Star Chapter: SANCTUARY [Lover]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tsc-lover.webp",
  },
  {
    artist: "TXT",
    albumName: "The Star Chapter: TOGETHER [Awake]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tsc-awake.webp",
  },
  {
    artist: "TXT",
    albumName: "The Star Chapter: TOGETHER [Etched]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tsc-etched.webp",
  },
  {
    artist: "TXT",
    albumName: "The Star Chapter: TOGETHER [Starlight]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "tsc-starlight.webp",
  },
  {
    artist: "TXT",
    albumName: "Beomgyu's Mixtape - Panic",
    owned: false,
    wishlist: true,
    notes: "",
    img: "panic.png",
  },
  {
    artist: "The Boyz",
    albumName: "Lightstick",
    owned: false,
    wishlist: true,
    notes: "",
    img: "tbz-lightstick.webp",
  },
  {
    artist: "The Boyz",
    albumName: "THE FIRST [Live]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "first-live.webp",
  },
  {
    artist: "The Boyz",
    albumName: "THE FIRST [Fresh]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "first-fresh.webp",
  },
  {
    artist: "The Boyz",
    albumName: "THE START [Set]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "start-set.webp",
  },
  {
    artist: "The Boyz",
    albumName: "THE START [Go]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "start-go.webp",
  },
  {
    artist: "The Boyz",
    albumName: "THE SPHERE [Real]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "sphere-real.webp",
  },
  {
    artist: "The Boyz",
    albumName: "THE SPHERE [Dream]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "sphere-dream.webp",
  },
  {
    artist: "The Boyz",
    albumName: "The Only [No Air]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "only-noair.webp",
  },
  {
    artist: "The Boyz",
    albumName: "The Only [In The Air]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "only-intheair.jpeg",
  },
  {
    artist: "The Boyz",
    albumName: "The Only [Off Air]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "defaultimg.webp",
  },
  {
    artist: "The Boyz",
    albumName: "Bloom Bloom [Bloom]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "defaultimg.webp",
  },
  {
    artist: "The Boyz",
    albumName: "Bloom Bloom [Heart]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "defaultimg.webp",
  },
  {
    artist: "The Boyz",
    albumName: "DREAMLIKE [Dreamlike]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "dreamlike-dreamlike.webp",
  },
  {
    artist: "The Boyz",
    albumName: "DREAMLIKE [Day]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "dreamlike-day.webp",
  },
  {
    artist: "The Boyz",
    albumName: "DREAMLIKE [DIY]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "dreamlike-diy.webp",
  },
  {
    artist: "The Boyz",
    albumName: "REVEAL [Wolf]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "reveal-wolf.webp",
  },
  {
    artist: "The Boyz",
    albumName: "REVEAL [Moon]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "reveal-moon.webp",
  },
  {
    artist: "The Boyz",
    albumName: "REVEAL [Boy]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "reveal-boy.webp",
  },
  {
    artist: "The Boyz",
    albumName: "CHASE [Chase]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "chase-chase.webp",
  },
  {
    artist: "The Boyz",
    albumName: "CHASE [Stealer]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "chase-stealer.webp",
  },
  {
    artist: "The Boyz",
    albumName: "CHASE [Trick]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "chase-trick.webp",
  },
  {
    artist: "The Boyz",
    albumName: "THRILL-ING [Kick]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "thrilling-kick.webp",
  },
  {
    artist: "The Boyz",
    albumName: "THRILL-ING [Bang]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "thrilling-bang.webp",
  },
  {
    artist: "The Boyz",
    albumName: "THRILL-ING [Splash]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "thrilling-splash.webp",
  },
  {
    artist: "The Boyz",
    albumName: "MAVERICK [Doom]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "maverick-doom.webp",
  },
  {
    artist: "The Boyz",
    albumName: "MAVERICK [Mood]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "maverick-mood.webp",
  },
  {
    artist: "The Boyz",
    albumName: "MAVERICK [Story Book]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "maverick-storybook.webp",
  },
  {
    artist: "The Boyz",
    albumName: "BE AWARE [Denial]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "aware-denial.webp",
  },
  {
    artist: "The Boyz",
    albumName: "BE AWARE [Desire]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "aware-desire.webp",
  },
  {
    artist: "The Boyz",
    albumName: "BE AWARE [Document]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "aware-document.webp",
  },
  {
    artist: "The Boyz",
    albumName: "BE AWAKE [Reach]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "awake-reach.webp",
  },
  {
    artist: "The Boyz",
    albumName: "BE AWAKE [Realize]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "awake-realize.webp",
  },
  {
    artist: "The Boyz",
    albumName: "BE AWAKE [Reason]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "awake-reason.webp",
  },
  {
    artist: "The Boyz",
    albumName: "PHANTASY Pt.1 Christmas in August [Holiday]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "phantasy1-holiday.webp",
  },
  {
    artist: "The Boyz",
    albumName: "PHANTASY Pt.1 Christmas in August [Glitter]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "phantasy1-glitter.webp",
  },
  {
    artist: "The Boyz",
    albumName: "PHANTASY Pt.1 Christmas in August [Present]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "phantasy1-present.webp",
  },
  {
    artist: "The Boyz",
    albumName: "PHANTASY Pt.2 Sixth Sense [Warn]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "phantasy2-warn.webp",
  },
  {
    artist: "The Boyz",
    albumName: "PHANTASY Pt.2 Sixth Sense [Daze]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "phantasy2-daze.webp",
  },
  {
    artist: "The Boyz",
    albumName: "PHANTASY Pt.2 Sixth Sense [Fake]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "phantasy2-fake.webp",
  },
  {
    artist: "The Boyz",
    albumName: "PHANTASY Pt.3 Love Letter [Write]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "phantasy3-write.webp",
  },
  {
    artist: "The Boyz",
    albumName: "PHANTASY Pt.3 Love Letter [Send]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "phantasy3-send.webp",
  },
  {
    artist: "The Boyz",
    albumName: "TRIGGER [Flash]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "defaultimg.webp",
  },
  {
    artist: "The Boyz",
    albumName: "TRIGGER [Riot]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "defaultimg.webp",
  },
  {
    artist: "The Boyz",
    albumName: "TRIGGER [Vanguard]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "defaultimg.webp",
  },
  {
    artist: "The Boyz",
    albumName: "Unexpected [Begin]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "unexpected-begin.webp",
  },
  {
    artist: "The Boyz",
    albumName: "Unexpected [Become]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "unexpected-become.webp",
  },
  {
    artist: "The Boyz",
    albumName: "Unexpected [Breakthrough]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "unexpected-breakthrough.webp",
  },
  {
    artist: "The Boyz",
    albumName: "a;effect [Movement]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "aeffect-movement.jpg",
  },
  {
    artist: "The Boyz",
    albumName: "a;effect [Vision]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "aeffect-vision.webp",
  },
  {
    artist: "Astro",
    albumName: "Lightstick [Ver.2]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "astro-lightstick2.webp",
  },
  {
    artist: "Astro",
    albumName: "Lightstick [Ver.3]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "astro-lightstick3.webp",
  },
  {
    artist: "Astro",
    albumName: "All Light [Green]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "alllight-green.webp",
  },
  {
    artist: "Astro",
    albumName: "All Light [White]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "alllight-white.webp",
  },
  {
    artist: "Astro",
    albumName: "Blue Flame [The Story]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "blueflame-story.webp",
  },
  {
    artist: "Astro",
    albumName: "Blue Flame [The Book]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "blueflame-book.webp",
  },
  {
    artist: "Astro",
    albumName: "Gateway [Time Traveller]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "gateway-time.png",
  },
  {
    artist: "Astro",
    albumName: "Gateway [Another World]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "gateway-another.png",
  },
  {
    artist: "Astro",
    albumName: "All Yours [You]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "allyours-you.webp",
  },
  {
    artist: "Astro",
    albumName: "All Yours [Me]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "allyours-me.webp",
  },
  {
    artist: "Astro",
    albumName: "All Yours [Us]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "allyours-us.webp",
  },
  {
    artist: "Astro",
    albumName: "Switch On [On]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "switchon-on.webp",
  },
  {
    artist: "Astro",
    albumName: "Switch On [Off]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "switchon-off.webp",
  },
  {
    artist: "Astro",
    albumName: "Drive to the starry road [Drive]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "dttsr-drive.webp",
  },
  {
    artist: "Astro",
    albumName: "Drive to the starry road [Starry]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "dttsr-starry.webp",
  },
  {
    artist: "Astro",
    albumName: "Drive to the starry road [Road]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "dttsr-road.webp",
  },
  {
    artist: "Ghost9",
    albumName: "PRE EPISODE 1 : DOOR",
    owned: true,
    wishlist: false,
    notes: "",
    img: "preep1-door.webp",
  },
  {
    artist: "Ghost9",
    albumName: "PRE EPISODE 2 : W.ALL",
    owned: true,
    wishlist: false,
    notes: "",
    img: "preep2-wall.webp",
  },
  {
    artist: "Ghost9",
    albumName: "NOW : Where we are, here",
    owned: true,
    wishlist: false,
    notes: "",
    img: "now-here.webp",
  },
  {
    artist: "Ghost9",
    albumName: "NOW : When we are in Love",
    owned: true,
    wishlist: false,
    notes: "",
    img: "now-love.webp",
  },
  {
    artist: "Ghost9",
    albumName: "NOW : Who we are facing",
    owned: false,
    wishlist: true,
    notes: "",
    img: "now-facing.webp",
  },
  {
    artist: "Ghost9",
    albumName: "ARCADE : V [Twilight]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "arcade-twilight.webp",
  },
  {
    artist: "Ghost9",
    albumName: "ARCADE : V [Mystery]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "arcade-mystery.webp",
  },
  {
    artist: "Ghost9",
    albumName: "ARCADE : O [Black]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "arcade-black.webp",
  },
  {
    artist: "Ghost9",
    albumName: "ARCADE : O [Yellow]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "arcade-yellow.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Lightstick [Ver.1]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "skz-lightstick1.png",
  },
  {
    artist: "Stray Kids",
    albumName: "Lightstick [Ver.2]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "skz-lightstick2.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "PuppyM Plush",
    owned: false,
    wishlist: true,
    notes: "",
    img: "puppym-original.jpg",
  },
  {
    artist: "Stray Kids",
    albumName: "PuppyM Plush [Magic School 10cm]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "puppym-magicschool.jpg",
  },
  {
    artist: "Stray Kids",
    albumName: "Mixtape",
    owned: false,
    wishlist: false,
    notes: "",
    img: "skz-mixtape.jpg",
  },
  {
    artist: "Stray Kids",
    albumName: "I am NOT [I AM]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "iamnot-iam.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "I am NOT [NOT]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "iamnot-not.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "I am WHO? [I AM]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "iamwho-iam.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "I am WHO? [WHO]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "iamwho-who.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "I am YOU [I AM]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "iamyou-iam.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "I am YOU [YOU]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "iamyou-you.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Clé 1: Miroh [Clé 1]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "cle1-cle.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Clé 1: Miroh [Miroh]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "cle1-miroh.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Clé 2: Yellow Wood [Clé 2]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "cle2-cle.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Clé 2: Yellow Wood [Yellow Wood]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "cle2-yellow.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Clé: Levanter [Clé]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "cle-cle.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Clé 2: Levanter [Levanter]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "cle-levanter.png",
  },
  {
    artist: "Stray Kids",
    albumName: "Go生 [A]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "golive-a.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Go生 [B]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "golive-b.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Go生 [C]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "golive-c.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Go生 [Limited]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "golive-limited.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "In Life [A]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "inlife-a.jpg",
  },
  {
    artist: "Stray Kids",
    albumName: "In Life [B]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "inlife-b.jpg",
  },
  {
    artist: "Stray Kids",
    albumName: "NOEASY [A]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "noeasy-a.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "NOEASY [B]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "noeasy-b.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "NOEASY [Limited]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "noeasy-limited.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "NOEASY [Seungmin]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "noeasy-seungmin.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Christmas EveL [Standard]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "xmasevel-standard.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Christmas EveL [Limited]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "xmasevel-limited.jpeg",
  },
  {
    artist: "Stray Kids",
    albumName: "ODDINARY [Scanning]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "oddinary-scanning.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "ODDINARY [Mask Off]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "oddinary-maskoff.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "ODDINARY [Frankenstein]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "oddinary-frankenstein.jpg",
  },
  {
    artist: "Stray Kids",
    albumName: "ODDINARY [Seungmin]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "oddinary-seungmin.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Maxident [T-Crush]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "maxident-tcrush.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Maxident [Heart]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "maxident-heart.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "Maxident [Go]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "maxident-go.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "★★★★★ (5 STAR) [A]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "5star-a.jpg",
  },
  {
    artist: "Stray Kids",
    albumName: "★★★★★ (5 STAR) [B]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "5star-b.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "★★★★★ (5 STAR) [C]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "5star-c.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "樂-STAR (ROCK-STAR) [Rock]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "defaultimg.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "樂-STAR (ROCK-STAR) [Roll]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "defaultimg.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "樂-STAR (ROCK-STAR) [Star]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "defaultimg.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "ATE [Chk Chk]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "ate-chkchk.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "ATE [Boom]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "ate-boom.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "ATE [Ate]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "ate-ate.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "合 (HOP) [SKZHOP]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "hop-skzhop.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "合 (HOP) [HIPTAPE]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "hop-hiptape.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "KARMA [Ceremony]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "karma-ceremony.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "KARMA [Hooray]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "karma-hooray.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "KARMA [Karma]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "karma-karma.png",
  },
  {
    artist: "Stray Kids",
    albumName: "KARMA [SKZOO]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "karma-skzoo.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "KARMA [Seungmin]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "karma-seungmin.webp",
  },
  {
    artist: "Stray Kids",
    albumName: "DO IT [IT]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "doit-it.png",
  },
  {
    artist: "Stray Kids",
    albumName: "DO IT [DO]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "doit-do.png",
  },
  {
    artist: "Stray Kids",
    albumName: "DO IT [Seungmin]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "doit-seungmin.png",
  },
  {
    artist: "Ateez",
    albumName: "Lightstick [Ver.1]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "atz-lightstick1.jpg",
  },
  {
    artist: "Ateez",
    albumName: "Lightstick [Ver.2]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "atz-lightstick2.jpeg",
  },
  {
    artist: "Ateez",
    albumName: "TREASURE EP.1: All to Zero",
    owned: false,
    wishlist: false,
    notes: "",
    img: "treasure1.webp",
  },
  {
    artist: "Ateez",
    albumName: "TREASURE EP.2: Zero to One",
    owned: false,
    wishlist: false,
    notes: "",
    img: "treasure2.webp",
  },
  {
    artist: "Ateez",
    albumName: "TREASURE EP.3: One to All [Wave]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "treasure3-wave.webp",
  },
  {
    artist: "Ateez",
    albumName: "TREASURE EP.3: One to All [Illusion]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "treasure3-illusion.webp",
  },
  {
    artist: "Ateez",
    albumName: "TREASURE EP.FIN: All to Action [A]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "treasurefin-a.jpg",
  },
  {
    artist: "Ateez",
    albumName: "TREASURE EP.FIN: All to Action [Z]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "treasurefin-z.jpg",
  },
  {
    artist: "Ateez",
    albumName: "TREASURE EP.EPILOGUE: Action to Answer [A]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "treasureep-a.jpg",
  },
  {
    artist: "Ateez",
    albumName: "TREASURE EP.EPILOGUE: Action to Answer [Z]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "treasureep-z.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER Part.1 [Thanxx]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "zero1-thanxx.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER Part.1 [Inception]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "zero1-inception.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER Part.1 [Diary]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "zero1-diary.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER Part.2 [A]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "zero2-a.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER Part.2 [Diary]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "zero2-diary.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER Part.2 [Z]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "zero2-z.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER Part.3 [A]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "zero3-a.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER Part.3 [Diary]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "zero3-diary.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER Part.3 [Z]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "zero3-z.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER EPILOGUE [A]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "zeroep-a.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER EPILOGUE [Diary]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "zeroep-diary.jpg",
  },
  {
    artist: "Ateez",
    albumName: "ZERO : FEVER EPILOGUE [Z]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "zeroep-z.jpg",
  },
  {
    artist: "Ateez",
    albumName: "THE WORLD EP.1 : MOVEMENT [A]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "theworld1-a.jpg",
  },
  {
    artist: "Ateez",
    albumName: "THE WORLD EP.1 : MOVEMENT [Diary]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "theworld1-diary.jpg",
  },
  {
    artist: "Ateez",
    albumName: "THE WORLD EP.1 : MOVEMENT [Z]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "theworld1-z.jpg",
  },
  {
    artist: "Ateez",
    albumName: "THE WORLD EP.2 : OUTLAW [A]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "theworld2-a.jpg",
  },
  {
    artist: "Ateez",
    albumName: "THE WORLD EP.2 : OUTLAW [Diary]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "theworld2-diary.jpg",
  },
  {
    artist: "Ateez",
    albumName: "THE WORLD EP.2 : OUTLAW [Z]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "theworld2-z.jpg",
  },
  {
    artist: "Ateez",
    albumName: "THE WORLD EP.FIN : WILL [A]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "theworld3-a.jpg",
  },
  {
    artist: "Ateez",
    albumName: "THE WORLD EP.FIN : WILL [Diary]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "theworld3-diary.jpg",
  },
  {
    artist: "Ateez",
    albumName: "THE WORLD EP.FIN : WILL [Z]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "theworld3-z.jpg",
  },
  {
    artist: "Ateez",
    albumName: "GOLDEN HOUR : Part.1 [Blue Hour]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "goldenhour1-bluehour.jpg",
  },
  {
    artist: "Ateez",
    albumName: "GOLDEN HOUR : Part.1 [Diary]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "goldenhour1-diary.jpg",
  },
  {
    artist: "Ateez",
    albumName: "GOLDEN HOUR : Part.1 [Golden Hour]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "goldenhour1-goldenhour.jpg",
  },
  {
    artist: "Ateez",
    albumName: "GOLDEN HOUR : Part.2 [To]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "goldenhour2-to.png",
  },
  {
    artist: "Ateez",
    albumName: "GOLDEN HOUR : Part.2 [Diary]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "goldenhour2-diary.png",
  },
  {
    artist: "Ateez",
    albumName: "GOLDEN HOUR : Part.2 [For]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "goldenhour2-for.png",
  },
  {
    artist: "Ateez",
    albumName: "GOLDEN HOUR : Part.3 [Group]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "goldenhour3-group.png",
  },
  {
    artist: "Ateez",
    albumName: "GOLDEN HOUR : Part.3 'In Your Fantasy Edition' [Red]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "goldenhour3-red.webp",
  },
  {
    artist: "Ateez",
    albumName: "GOLDEN HOUR : Part.3 'In Your Fantasy Edition' [Black]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "goldenhour3-black.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Border: Day One [Dusk]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "border-dusk.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Border: Day One [Dawn]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "border-dawn.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Border: Carnival [Up]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "border-up.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Border: Carnival [Hype]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "border-hype.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Border: Carnival [Down]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "border-down.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Dimension: Dilemma [Scylla]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "dimension-scylla.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Dimension: Dilemma [Odysseus]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "dimension-odysseus.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Dimension: Dilemma [Charybdis]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "dimension-charybdis.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Dimension: Answer [No]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "dimension-no.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Dimension: Dilemma [Yet]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "dimension-yet.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Manifesto: Day 1 [D]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "manifesto-d.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Manifesto: Day 1 [J]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "manifesto-j.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Manifesto: Day 1 [M]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "manifesto-m.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Dark Blood [Full]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "darkblood-full.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Dark Blood [Half]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "darkblood-half.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Dark Blood [New]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "darkblood-new.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Dark Blood [Engene]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "darkblood-engene.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Orange Blood [Ksana]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "orangeblood-ksana.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Orange Blood [Kalpa]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "orangeblood-kalpa.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Memorabilia [Moon]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "memorabilia-moon.jpg",
  },
  {
    artist: "Enhypen",
    albumName: "Memorabilia [Vargr]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "memorabilia-vargr.png",
  },
  {
    artist: "Enhypen",
    albumName: "Romance:Untold [Inceptio]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "romanceuntold-inceptio.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Romance:Untold [Arcanum]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "romanceuntold-arcanum.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Romance:Untold [Concessio]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "romanceuntold-concessio.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Romance:Untold Daydream [Blue Noon]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "romanceuntold-bluenoon.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Romance:Untold Daydream [White Midnight]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "romanceuntold-whitemidnight.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Desire:Unleashed [Make]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "du-make.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Desire:Unleashed [You]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "du-you.webp",
  },
  {
    artist: "Enhypen",
    albumName: "Desire:Unleashed [Mine]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "du-mine.webp",
  },
  {
    artist: "Twice",
    albumName: "Fancy You [A]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "fancyyou-a.webp",
  },
  {
    artist: "Seventeen",
    albumName: "Boys Be [Hide]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "boysbe-hide.jpg",
  },
  {
    artist: "Seventeen",
    albumName: "FML [Carat]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "fml-carat.jpg",
  },
  {
    artist: "Seventeen",
    albumName: "Sector 17 [Compact]",
    owned: true,
    wishlist: false,
    notes: "",
    img: "sector17-compact.jpg",
  },
  {
    artist: "Pentagon",
    albumName: "Love or Take [Romantic]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "loveortake-romantic.webp",
  },
  {
    artist: "Pentagon",
    albumName: "Love or Take [Sporty]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "loveortake-sporty.jpg",
  },
  {
    artist: "Pentagon",
    albumName: "Love or Take [Mild]",
    owned: false,
    wishlist: false,
    notes: "",
    img: "loveortake-mild.jpg",
  },
  {
    artist: "Lesserafim",
    albumName: "Hot [Vol. 2 Tanned Guaiac]",
    owned: false,
    wishlist: true,
    notes: "",
    img: "hot-tannedguaiac.jpg",
  },
];

export default allAlbums;
